---
title: "NY Times Semantic API"
author: "Justin Williams"
date: "3/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, message=FALSE, warning=FALSE}
library(dotenv)
library(jsonlite)
library(tidyverse)
```

## Overview

This RMD will demonstrate working with the NY Times Semantic API.

### Load in data

```{r make-api-call}
# load up hidden api key
api_key <- Sys.getenv("NYTIMES_API")

# set base url
base_url <- "http://api.nytimes.com/svc/semantic/v2/concept/search.json?"

# set parameters
term <- "greenhouse+gas"
concept_type <- "nytd_des"
begin_date <- "19810101"
end_date <- "20211231"

# import dataset to R
fromJSON(paste0(base_url,"query=",term,"&concept_type=",concept_type,"&api-key=",api_key,sep = ""), flatten = T)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
